language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
    - secure: XGnyNKOtSYUtSCykfSF0rDTjyrXK7s4WbcsesoWjhfxgPaH8Gu/xejAe72yRI3Q059uGJzBs3ehoUkexCu41OfvsdC8gxPH+6CikjNsvI2hmQWNTuYdP1OY78z/8tUxr3Q5v4znTsWAT/A7bxQ2sYqZbnAmSQnF9JvYbjKMHUf/9I6291UBDkUfp5iKL/ELcAFT6mAemZDei/VKmhoWXFoDis+sa6Np9ISv4b32vFvDW96a99tYYyWSc4Kmmso5/Dvpcwk+JQXUCJc8JslweH568G2IRgZ7sg2wsf+K8/wkBmCA2x1xMv3+UpkxljUMek3UdXKf2TY0JnHPkrNnxlnacwmc6JedbJytRdSt1FIw6a7gCn536iMOTH/Ntvu09zQdp18Aato4sC/SgSH6PfWEAhl0B0dEQIGb4EbEJ9NDcixGmlvWXtDESfkEN0XaFTTS8DgoqLZRXreJr9KBzz1ih5vykRYfdPMfGrGKP9OUZ+wrL0s3o98dkWPFly73gr35wbzj2nJ35hpfoX7Op754OgN0njx9mxz0/CBTNjAWCQBGnOKsu2cBeXE7yZ08JhJBcEyXrAOsPzdKLOFLXjNO2oZB3eg1H4ReucaG1tlfh5QsNjnFYJLseV65mcear4g+bdQBvFCM8vxJIvn7edcWy8P+cuPIA6d8spSvB46c=
    - secure: A5ni1MwAXO6IDDfaC2F8qqEo1ckljbjrCCylb1WKByCIsiVDO7KXQ5+jtWFwKKlIG98mdqjdI10Kp/2SfBC7ZHt1L7e+tcehFOexCH71Fs1ujk5wn3KQstfHMnv2xhxiVozYD8HqWB/cRbe8Yra6r9+5Dk6NeWfPAPlCHMcWAZ4kRHS8KNQ4nL9AjTtPRY75cOcUKP3vmEi1eBtd+cswPjhGUZRZkW7cXY32Ws6oYQSMjvuCQqYmCNs/VjjPku1gfPLzqcrRtmG2nQdznae4yvqTO6lB7ZM3nta3FSR2qR8Vf4TyNQd5uWD2TJ9S4TmebvRT1QKdDkdCRLb1Cre8TyrdULvOOcdRcMwvFTrinxVpIzYedodY19CfzQcuBBj2xRZNDRayAXencR7Q8Wi1HHxS5+6BeWzZ+sj20ncV6HDGtPbJro7Ge4GAPpKo9VMHdy3iOfT2OTswishFWrZfenctxOAFZ37EfoIVunizm6CnmYznkhz/2Jsjbc4GICLwOd2EXboWt9gH3jkf4/SHDaBNe/okyTmV105A0Ax2rZXbFuPrMWfmliwZ40WnUd08l24OVKb8dHdgNikRFkwUIyi4ZC8uhZEGUewtXIhWERqfYxWjEkFm881t+XR0+OP15jBW0rIwT4TFBs61CRIqoPIXAYv7FGhXU+M9mUYbvEk=
